# Runs Bazel tests for DeepMind Lab

os: osx

env:
  - BUILD_TYPE=osmesa

language: c++

addons:
  homebrew:
    taps:
      - bazelbuild/tap
      - homebrew/cask-versions
    casks:
      - java8

before_install:
  - brew install bazel glib sdl2

script:
  - bazel build -c opt --copt=-Wno-sign-compare --apple_platform_type=macos --show_progress_rate_limit=10 --dynamic_mode=off //:game //:game_lib_headless_macos //deepmind/... //q3map2/... //testing/... //lua_tests/... && bazel test -c opt --copt=-Wno-sign-compare --apple_platform_type=macos --dynamic_mode=off //deepmind/... 
